version: '3'

services: 
    mysql-dev:
        image: mysql:8.0.2
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test_ db
        ports: 
            - "3308:3306"
        volumes: 
            - "./data:/var/lib/msql:rw"

    postres-dev:
        image: postgres:12.2
         environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: dev_db

        ports: 
            - "5433:5432" 
        volumes: 
            - "./data:/var/lib/postgresql/data"